### PR TITLE
Local container testing

### PR DESCRIPTION
**Pull request by goyder**
*Issue #, if available:* n/a

*Description of changes:*

* Updates SageMaker version in all modules to >2.22.0 _(required for local Processor mode)_
* Updates SageMaker version to include `[local]` option for local Docker usage
* Add `test_local_deployments.py` test under `mlmax` test suite 
  * Tests are configured to only run if command line argument `--smlocal` is supplied to `pytest`
* Local deployment tests will run in Python inspect mode (e.g. `python -i entrypoint.py`) if the additional argument `--inspectlocal` is supplied
  * This means that the container instances will not exit on completion and can be explored via Docker; this is a very useful feature for troubleshooting container integration. 
  * As a downside, tests must be manually ended with `ctrl-c` in these mode and will always result in a failure
  * Instructions for inspecting individual tests are provided

*Suggested discussion points*

- Do these local deployment tests below under the root `mlmax` module, or are they better placed under the `pipeline` module?
  - They are currently under the `mlmax` module as they are essentially testing `mlmax` code and accessing the associated test data. However, it could be considered that this work is more suitable for the `pipeline` module given its integration focus.
- Is there are better place for documentation regarding these tests than `test_local_deployments.py`?
- There does not seem to be a way to inject environment variables in the `SKLearn` training container (the function arguments that should do not *actually* pass anything in); therefore, a slightly jankier "hyperparameter" based approach has been implemented. However, this requires the training code to be modified to serve the purposes of container debugging, which is not ideal. Is there any way to inject environment variables into an SKLearn training container or otherwise trigger the Python inspect mode?
- Are there any issues with moving to SageMaker 2.x?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by goyder** [comment]
Following conversation with team members:

> Is there are better place for documentation regarding these tests than test_local_deployments.py?

Yes - these are better broken out into stand-alone `README.md` docs, and has been included in a new commit.

> There does not seem to be a way to inject environment variables in the `SKLearn` training container (the function arguments that should do not actually pass anything in); therefore, a slightly jankier "hyperparameter" based approach has been implemented. However, this requires the training code to be modified to serve the purposes of container debugging, which is not ideal. Is there any way to inject environment variables into an SKLearn training container or otherwise trigger the Python inspect mode?

Following discussion with @verdimrc, there does not appear to be a way to inject environment variables in training calls and this must be accomplished by hyperparameters. This is the current method implemented in this branch.

**Comment by josiahdavis** [comment]
Thanks for your PR @goyder! Few minor comments:

1. In the documentation/readme, could you include the full command you would like the user to run? e.g., `PYTHONPATH=./src pytest --smlocal`?
2. Can you clairfy in the documentation that once you run the inspectlocal bit the test will appear to hang. Open up a new terminal session and enter the following: 1. `docker ps` ....
3. I believe the docker run command should be `docker exec -it <container ID> /bin/bash`.
4. Can you include an example reference for inspect local, e.g., check out `opt/ml/processing` which looks something like this:

```
opt/ml/processing/
├── input
│   ├── census-income-sample.csv
│   ├── code
│   │   └── preprocessing.py
│   └── test_features.csv
├── model
├── test
└── train
```

5. You mentioned preferring not to modify the original src/mlmax/*.py files. I agree. Can you clarify why it is required for train.py and not for any other files? Also, is this environment variable being set within the container? If this is not the case, one option might be to set the environment variable at runtime e.g., `PYTHONINSPECT=1 pytest ....`

**Comment by josiahdavis** [comment]
> There does not seem to be a way to inject environment variables in the SKLearn training container...

@goyder, as noted by @verdimrc, SageMaker Training jobs (recently updated) now accepts environment variables: https://github.com/aws/sagemaker-python-sdk/commit/773c61b7f3958bf861d7d23cfe6f46bfe6ef9227

Did you try this approach?

**Comment by goyder** [comment]
> Thanks for your PR @goyder! Few minor comments:
> 
>     1. In the documentation/readme, could you include the full command you would like the user to run? e.g., `PYTHONPATH=./src pytest --smlocal`?
> 
>     2. Can you clairfy in the documentation that once you run the inspectlocal bit the test will appear to hang. Open up a new terminal session and enter the following: 1. `docker ps` ....
> 
>     3. I believe the docker run command should be `docker exec -it <container ID> /bin/bash`.
> 
>     4. Can you include an example reference for inspect local, e.g., check out `opt/ml/processing` which looks something like this:
> 
> 
> ```
> opt/ml/processing/
> ├── input
> │   ├── census-income-sample.csv
> │   ├── code
> │   │   └── preprocessing.py
> │   └── test_features.csv
> ├── model
> ├── test
> └── train
> ```

Done, good points feedback! Especially given the `--inspectlocal` mode is rather unintuitive. 

I've updated README.md with the commands to run the test (which is generally just `$ pytest` - the test suite should run from root). 

Further, I've listed them in the format of 
```bash
user@machine:<folder>$ <command>
```
which becomes particularly relevant once the instructions cover hopping into the container with `docker exec`. 

I've expanded the `--inspectlocal` section to walk through a full typical workflow. 

Please let me know if there's anything else you'd like to add!

>     1. You mentioned preferring not to modify the original src/mlmax/*.py files. I agree. Can you clarify why it is required for train.py and not for any other files? Might one option might be to set the environment variable at runtime e.g., `PYTHONINSPECT=1 pytest ....`?
> @goyder, as noted by @verdimrc, SageMaker Training jobs (recently updated) now accepts environment variables: aws/sagemaker-python-sdk@773c61b
> 
> Did you try this approach?

As that update indicates, it take the variables passed in by the `environment` and inject them into the container. Unfortunately the SKLearn container doesn't honour this API defined by the `estimator`, and there's no other way (that I or @verdimrc have discovered) to inject environment variables. 

I've raised this as an issue on the SKLearn container repo: https://github.com/aws/sagemaker-scikit-learn-container/issues/81. In the meantime, this hyperparameter solution is a "minimally invasive" workaround - when the above issue is addressed it can be gladly removed.

**Comment by josiahdavis** [comment]
+1

**Review by josiahdavis — APPROVED** [review]

**Comment by josiahdavis** [comment]
Thanks @goyder! Looks good to me. 

Sorry, another nit... seems like the lint check runs into a minor issue with this line:

`if args.inspect == True:`

The error message is:

`src/mlmax/train.py:83:21: E712 comparison to True should be 'if cond is True:' or 'if cond:'`

If you can change that to `if args.inspect:` or `if args.inspect is True:` it should pass the check.

**Comment by josiahdavis** [comment]
@goyder sorry, now its saying that's there's a black error. 

One quick tip: if you use the [pre-commit tool](https://pre-commit.com/), you can avoid all of these linting issues as it will auto-check the code format before you make a commit. 

In the interim, as a quick fix, you can run the formatting on a specific file like this:

`pre-commit run --files src/mlmax/train.py modules/pipeline/training_pipeline_define.py`

**Comment by goyder** [comment]
Apologies + whoops - I thought I had already configured these :) Should be all done now!

**Pull request merged**
