### PR TITLE
Self-contained screening of train and batch-transform permissions

### PR DESCRIPTION
**Pull request by verdimrc**
*Issue #, if available:* N/A

*Description of changes:* Self-contained notebook to validate that notebook's role has the necessary permissions to run processing, train, create model, and batch transform.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by josiahdavis** [comment]
Love this idea @verdimrc. 

Two questions:
* What are your thougths on including the smallmatter package? I wonder if it is something that some folks might not have access to and how much we could make this fully self-contained.
* Do you think we could put all of this great content in its own subfolder (in notebooks) e.g., notebooks/sagemaker-screen

**Comment by verdimrc** [comment]
> What are your thougths on including the smallmatter package? I'm just wondering if it is something that some folks might not have access to and how much we could make this fully self-contained.

That's a valid concern.

How about we document it clearly about the dependencies, and remind users with restricted access to bring in this smallmatter repo with the exact same way they did to mlmax repo? As for the rest users, they can still follow the same steps, or just install directly from github.

Other alternatives I can think off:

1. git submodule => to signal to users with restricted access that they need to bring in an additional repo, but bear in mind we'll be asking users to use different mechanics: one to bring in mlmax (however they want to do it), and then git submodule steps for the dependencies.

2. snapshot just the relevan portion of smallmatter (for now only two functions are used). In the long term, there may be risk of code divergence with the upstream.

> Do you think we could put all of this great content in its own subfolder (in notebooks) e.g., notebooks/screening

+1 on this.

**Comment by josiahdavis** [comment]
> How about we document it clearly about the dependencies, and remind users with restricted access to bring in this smallmatter repo with the exact same way they did to mlmax repo?

Sounds good! Thanks @verdimrc.

**Comment by yapweiyih** [comment]
Suggest to have a readme to describe the objective of this folder to encourage people to look into it.

**Comment by yapweiyih** [comment]
Tested to work with private VPC configuration.

**Review by yapweiyih — APPROVED** [review]

**Review by yihyap — APPROVED** [review]

**Pull request merged**
