### PR TITLE
Basic Continuous Integration using Tox and GitHub Actions

### PR DESCRIPTION
**Pull request by josiahdavis**
*Issue #, if available:* NA

*Description of changes:*
* Basic continuous integration using Tox and GitHub Actions

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by josiahdavis** [comment]
@verdimrc I'd like to get your feedback on the approach here for a GH Actions + tox based workflow.

**Comment by verdimrc** [comment]
Minor comments on `tox.ini`:
- under `[pytest]`, remove `--ignore=test/s3fscompat` (this was for another test that doesn't exist in this repo).
- pydocstyle: is the plan to enable this step in the actions? In my experience, its default setting might feel a bit too stringent to some, esp. for a stylistic / documentation aspect rather than for code correctness.

**Comment by verdimrc** [comment]
To remove `[testenv:reformat]` in `tox.ini`, as this won't be used in the actions.

**Comment by verdimrc** [comment]
Suggest a `[testenv:isort-check]`.

**Comment by josiahdavis** [comment]
> To remove `[testenv:reformat]` in `tox.ini`, as this won't be used in the actions.

Do you think it might be useful to keep it in there as a handy utility for folks who want to use it locally though?

**Comment by verdimrc** [comment]
> > To remove `[testenv:reformat]` in `tox.ini`, as this won't be used in the actions.
> 
> Do you think it might be useful to keep it in there as a handy utility for folks who want to use it locally though? 

pre-commit handles this case. (and fyi, that reformat entry predates precommit, so in a way it's a remnant from the past).

**Comment by josiahdavis** [comment]
> Minor comments on `tox.ini`:
> 
> * under `[pytest]`, remove `--ignore=test/s3fscompat` (this was for another test that doesn't exist in this repo).

Yes, I should have removed this one.

> * `pydocstyle`: is the plan to enable this step in the actions? In my experience, its default setting might feel a bit too stringent to some, esp. for a stylistic / documentation aspect rather than for code correctness.

Agreed it does feel too stringent, and I was not planning to put it into the CI. That said, on the fence about whether to leave it in their as on optional check or no.

**Review by verdimrc — APPROVED** [review]

**Pull request merged**
