### PR TITLE
Cicd pipeline

### PR DESCRIPTION
**Pull request by yinsong1986**
*Issue #23, if available: *

*Description of changes:*
- Add a time scheduler for the  inference pipeline.
- Initial CICD of the training and inference pipelines implementation using CodePipeline.
- Add support for cross account CICD

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yapweiyih** [comment]
@yinsong1986 One suggestion to have a script to create devops, stage, prod cross account roles. Created a samples script `create_roles.sh`.

**Comment by yinsong1986** [comment]
@yapweiyih Thx a lot! I just added you as reviewers. I will continue to clean the code this week, and it should be in a shape for you to try by end of this week.

**Comment by yinsong1986** [comment]
keep it alive.

**Comment by yinsong1986** [comment]
Hi team, merging this CICD branch to main branch for now:)

**Pull request merged**
